### ISSUE TITLE
UI modification of landing page, about, login ,signup 

### ISSUE THREAD

**Issue by shashisad** [Pranav016/BlogSite#17]
### **Additional context**

Note: If you want to work on an issue, you should check if it has already been assigned to anyone. If the issue is free you can comment `/assign` to get the issue assigned to you.
If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.

**Comment by Pranav016** [comment]
@shashisad Are you contributing as a part of GSSoC?

**Comment by shashisad** [comment]
@Pranav016 Ok
